---
title: "Clínica de Ciencia de datos"
description: "Especialización en Políticas Públicas"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Sobre el curso

Es un curso intensivo que se llevará a cabo en formato presencial durante los siguientes días y horarios:  
- Jueves 07/04 de 15 a 21hs.  
- Viernes 08/04 de 9 a 18hs.  
- Sábado 09/04 de 9 a 18hs.  
Cada encuentro tendrá una parte teórica donde los docentes presentarán los contenidos necesarios y donde diferentes invitados compartirán sus experiencias en el uso de datos en el sector público, y una parte práctica donde los alumnos trabajarán con las técnicas contempladas en el temario.

&nbsp;
&nbsp;

[**PROGRAMA**](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/programas/2022-EPP-CLINICA_DE_DATOS_PROGRAMA.pdf)


&nbsp;
&nbsp;

# Estructura del curso

## Día 1: jueves 7 de abril

### Clases teórico-prácticas

#### Práctica 1
Introducción a R y RStudio, instalación. Abrir el entorno y cargar un dataset.  

Manuales de clase:  
[Rpubs: Introducción a R](https://rpubs.com/angiescetta/presentacion-big-data-ciudad)



#### Práctica 2
Análisis exploratorio de datos: Data wrangling con tidyverse.

Manuales de clase:  
[Big data urbana: manipulación de datos](https://angiescetta.github.io/big-data-urbana/manipulaci%C3%B3n-de-datos.html)


### Desafío
[Consignas](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/desafio1.pdf) - [Descargar Rmd](epp-clinica/desafio1_template.Rmd) - [Descargar dataset](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/delitos2019-2020.csv) - [Link a repositorio](https://data.world/paulavidela/delitosgcba-2020-2019)

&nbsp;
&nbsp;


## Día 2: viernes 8 de abril

### Clases teórico-prácticas

#### Práctica 3
Visualización de datos: Introducción a ggplot.

Manuales de clase:  
[Big data urbana: Análisis y visualización](https://angiescetta.github.io/big-data-urbana/an%C3%A1lisis-y-visualizaci%C3%B3n-de-datos.html)



#### Práctica 4
Introducción a la manipulación de fechas y horas con lubridate. 

Manuales de clase:  
[Rpubs: Introducción a lubridate](https://rpubs.com/paulavidela/patronestemporales)


### Desafío
[Consignas](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/desafio2.pdf) - [Descargar Rmd](epp-clinica/desafio2_template.Rmd) - [Descargar dataset](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/delitos2019-2020.csv)


&nbsp;
&nbsp;

## Día 3: sábado 9 de abril

### Clases teórico-prácticas

#### Práctica 5
Información geográfica: introducción a sf - geoprocesos 

Manuales de clase:  
[Big data urbana: información geográfica](https://angiescetta.github.io/big-data-urbana/informaci%C3%B3n-geogr%C3%A1fica-y-mapas.html)
[Rpubs: Geoprocesamientos](https://rpubs.com/paulavidela/funciones-sf)


### Desafío
[Consignas](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/desafio3.pdf) - [Descargar Rmd](epp-clinica/desafio3_template.Rmd)  
[Descargar dataset 1: delitos](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/delitos2019-2020.csv) - [Descargar dataset 2: barrios](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/barrios.geojson) -  [Descargar dataset 3: barrios](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/epp-clinica/comunas.geojson)




