---
title: "Introducción a la Ciencia de Datos"
description: "Formación Ejecutiva en Políticas Públicas"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Sobre el curso

Es un curso introductorio a herramientas de Ciencias de Datos orientado a las políticas públicas. Se llevará a cabo en formato virtual durante los siguientes días y horarios:  
- Miércoles 03/08 de 19 a 21hs.   
- Miércoles 10/08 de 19 a 21hs.  
- Miércoles 17/08 de 19 a 21hs.   
- Miércoles 24/08 de 19 a 21hs.  
- Miércoles 31/08 de 19 a 21hs.   
&nbsp;

Para cada clase se prevé una breve introducción teórica. Luego se desarrollará un taller, durante el cual se pondrán en práctica las técnicas contempladas en el temario. Para fomentar la práctica de las nuevas herramientas, los participantes podrán realizar ejercicios para cada clase.

&nbsp;
&nbsp;

[**PROGRAMA**](https://github.com/paulavidela/utdt_cienciadedatos/raw/main/programas/2022-FEPP-INTRODUCCION_A_CIENCIA_DE_DATOS.pdf)


&nbsp;
&nbsp;

# Estructura del curso

**Clase 1: Big Data y Ciudad**  
Definiciones, análisis de casos, el futuro. Nuevos roles en la planificación urbana. Laboratorios de gobierno, oficinas de análisis de datos, promotores de datos abiertos. Introducción a R, el entorno para analizar, modelar, visualizar y comunicar con datos.  

&nbsp; 

**Clase 2: Análisis exploratorio y transformación de datos**  
Data wrangling: limpiando y ordenando datos. Técnicas fundamentales para la transformación de datos. Cruce de fuentes de datos. Introducción al paquete tidyverse.

&nbsp; 

**Clase 3: Visualización de datos**  
Narrando la ciudad con información. Cómo elegir la visualización adecuada para cada tipo de análisis.

&nbsp; 

**Clase 4: Manipulación y recodificación de fecha y hora**  
Analizar procesos espaciales a través del tiempo. Identificación de patrones: agrupando datos usando binning y gráficos de densidad. Introducción al paquete lubridate.

&nbsp; 

**Clase 5: Información geográfica y mapas**
Datos georreferenciados. Visualizando información geográfica. Capas y geometrías. Introducción al paquete sf.



